import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import RollingBackground from "@/components/layout/RollingBackground";

import Navbar from "@/components/layout/Navbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const zzzFont = localFont({
  src: '../public/fonts/inpin_hongmengti.ttf',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
return (
  <html lang="en" className="dark" suppressHydrationWarning>
        <body className={`${zzzFont.className} ${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
            <Navbar />
            <RollingBackground />

            <Suspense fallback={<div>Loading...</div>}>
                <div className="container mx-auto px-4 md:px-6 pt-5">
                    <div className="relative z-50 w-full flex flex-col overflow-y-hidden">
                        {children}
                    </div>
                </div>
            </Suspense>
        </body>
    </html>
  );
}
