import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RollingBackground from "@/components/layout/RollingBackground";

import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
return (
    <html lang="en" className="dark">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar />

            <div className="container mx-auto px-4 md:px-6 py-5">
                <RollingBackground />
                <div className="relative z-50 w-full flex flex-col overflow-y-hidden h-screen">
                    {children}
                </div>
            </div>
        </body>
    </html>
  );
}
